have_fun: false

memory_config:
  disabled: true

ignore_patterns:
  - "**/build/**"
  - "**/dist/**"
  - "**/generated/**"
  - "**/*.lock"
  - "**/*.md"

code_review:
  disable: false
  comment_severity_threshold: HIGH
  max_review_comments: 10
  pull_request_opened:
    help: false
    summary: true
    code_review: false
    include_drafts: false