name: Build JAR & Push Docker Image to GHCR (Org)

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build JAR
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/jobmanri-app:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/jobmanri-app:latest

  deploy-instance:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Upload run.sh to GCP Server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PEM_KEY }}
          source: "run.sh"
          target: "~/"
          overwrite: true

      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_PEM_KEY }}
          script: |
            echo "properties env ๋ฑ๋ก"
            echo "${{ secrets.PROD_ENV }}" > ~/.env
            
            echo "profile ๋ฑ๋ก"
            echo SPRING_PROFILES_ACTIVE=prod >> ~/.env
            
            echo "๐ GHCR ๋ก๊ทธ์ธ์ฉ PAT ์์ฉ"
            export GHCR_PAT="${{ secrets.GHCR_TOKEN }}"
            
            echo "๐ ์คํ ๊ถํ ๋ถ์ฌ"
            chmod +x ~/run.sh

            echo "๐ run.sh ์คํ"
            ~/run.sh

            echo "๐ ๋ฐฐํฌ ์๋ฃ!"